SELECT 
A.REST_ID,
A.REST_NAME,
A.FOOD_TYPE,
A.FAVORITES,
A.ADDRESS,
ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A
INNER JOIN REST_REVIEW AS B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC


# SELECT I.REST_ID,
#     I.REST_NAME,
#     I.FOOD_TYPE,
#     I.FAVORITES,
#     I.ADDRESS,
#     ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO I
# INNER JOIN REST_REVIEW R
#     ON I.REST_ID = R.REST_ID
#     AND I.ADDRESS LIKE '서울%'
# GROUP BY R.REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC